---
name: バグ報告
about: バグや問題を報告する
title: '[fix] '
labels: ['fix']
assignees: ''

---

## バグの概要
<!-- バグの内容を簡潔に説明してください -->

## 再現手順
<!-- バグを再現するための手順を記載してください -->
1. 
2. 
3. 

## 期待される動作
<!-- 本来期待される正しい動作を説明してください -->

## 実際の動作
<!-- 実際に起こっている問題の動作を説明してください -->

## スクリーンショット
<!-- 該当する場合、スクリーンショットを添付してください -->

## 環境情報
<!-- バグが発生した環境について記載してください -->
- OS: 
- ブラウザ: 
- バージョン: 
- その他:

## 追加のコンテキスト
<!-- その他、参考になる情報があれば記載してください -->
