---
name: 機能要望
about: 新しい機能や改善を提案する
title: '[feat] '
labels: ['feat']
assignees: ''

---

## 機能の概要
<!-- 提案する機能を簡潔に説明してください -->

## 解決したい問題
<!-- この機能によって解決される問題や課題を説明してください -->

## 提案する解決策
<!-- どのような実装や機能が必要か、具体的に説明してください -->

## 代替案
<!-- 他に検討した方法があれば記載してください -->

## 追加のコンテキスト
<!-- その他、参考になる情報（スクリーンショット、参考リンクなど）があれば記載してください -->
