---
name: タスク
about: 開発タスク、改善、リファクタリングなど汎用的な作業項目の管理
title: '[task] '
labels: ['task']
assignees: ''

---

## タスクの概要
<!-- タスクの内容を簡潔に説明してください -->

## 目的・背景
<!-- このタスクが必要な理由や背景を説明してください -->

## 完了条件（DoD: Definition of Done）
<!-- このタスクが完了したと判断できる基準をリストアップしてください -->
- [ ] 
- [ ] 
- [ ] 

## 関連する Issue / PR
<!-- 関連する Issue や Pull Request があれば記載してください -->
- 関連 Issue: #
- 関連 PR: #

## 追加のコンテキスト
<!-- その他、参考になる情報があれば記載してください -->
